os.img: os.prg
	burnroms

os.prg: start.o init.o main.o renderer.o model.o events.o raster.o bitmaps.o rast_asm.o inputs.o psg.o music.o effects.o songdat.o isr.o isr_asm.o vbl.o super.o ikbd.o ikbdisr.o
	ld -o os.prg start.o init.o main.o crt0.o libc.a

start.o: start.s
	gen -L2 start.s

init.o: init.c
	cc68x -c init.c

bitmaps.o: bitmaps.c bitmaps.h
	cc68x -c bitmaps.c

main.o: main.c types.h model.h events.h renderer.h rast_asm.h inputs.h raster.h effects.h music.h psg.h isr.h isr_asm.h vbl.h globals.h super.h ebh.h
	cc68x -c -g main.c

super.o: super.c super.h globals.h
	cc68x -c super.c 

effects.o: effects.c psg.h types.h sndconst.h super.h
	cc68x -c effects.c 

events.o: events.c model.h types.h raster.h effects.c psg.h
	cc68x -c events.c

inputs.o: inputs.c types.h inputs.h raster.h events.h
	cc68x -c inputs.c

isr.o: isr.c isr_asm.h
	cc68x -c isr.c

isr_asm.o: isr_asm.s isr.h
	gen -D -L2 isr_asm.s

vbl.o: vbl.c vbl.h types.h globals.h events.h model.h music.h psg.h
	cc68x -c vbl.c

model.o: model.c model.h types.h
	cc68x -c model.c

music.o: music.c music.h psg.h types.h songdat.h sndconst.h
	cc68x -c music.c 

psg.o: psg.c psg.h types.h
	cc68x -c psg.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

raster.o: raster.c types.h raster.h
	cc68x -c raster.c

renderer.o: renderer.c types.h model.h renderer.h bitmaps.h raster.h events.h effects.h psg.h super.h
	cc68x -c renderer.c

songdat.o: songdat.c songdat.h sndconst.h types.h
	cc68x -c songdat.c

ikbd.o: ikbd.c isr.h super.h types.h globals.h
	cc68x -c ikbd.c 

ikbdisr.o: ikbdisr.s ikbdisr.h
	gen -D -L2 ikbdisr.s
