TARGET_A=psg_tst
OBJECTS_A=psg_tst.o psg.o 

TARGET_B=mus_tst
OBJECTS_B=mus_tst.o music.o 

TARGET_C=eff_tst
OBJECTS_C=eff_tst.o effects.o 

CC=cc68x
CFLAGS=-g

# Building the target
all: clean $(TARGET_A) $(TARGET_B) $(TARGET_C)

# Linking target executable from object files
$(TARGET_A): $(OBJECTS_A)
	$(CC) $(OBJECTS_A) -o $(TARGET_A)

# Linking target executable from object files
$(TARGET_B): $(OBJECTS_B)
	$(CC) $(OBJECTS_B) -o $(TARGET_B)

# Linking target executable from object files
$(TARGET_C): $(OBJECTS_C)
	$(CC) $(OBJECTS_C) -o $(TARGET_C)

psg_tst.o: psg_tst.c psg.h types.h notefrqs.h
	$(CC) $(CFLAGS) -c psg_tst.c

mus_tst.o: mus_tst.c psg.h types.h notefrqs.h 
	$(CC) $(CFLAGS) -c mus_tst.c

eff_tst.o: eff_tst.c psg.h types.h notefrqs.h 
	$(CC) $(CFLAGS) -c eff_tst.c

psg.o: psg.c psg.h types.h
	$(CC) $(CFLAGS) -c psg.c

music.o: music.c psg.h types.h 
	$(CC) $(CFLAGS) -c music.c 

effects.o: effects.c psg.h types.h notefrqs.h
	$(CC) $(CFLAGS) -c effects.c 

# Cleaning up the old object files and executable
clean:
	$(RM) *.o $(TARGET_A) $(TARGET_B) $(TARGET_C)

# DON'T DELETE THIS LINE OR IT BREAKS