render: tst_rend.o renderer.o raster.o model.o a_map.o s_map.o d_map.o f_map.o one_map.o x_map.o zro_map.o
	cc68x -g tst_rend.o renderer.o raster.o model.o a_map.o s_map.o d_map.o f_map.o one_map.o x_map.o zro_map.o -o render

tst_rend.o: tst_rend.c TYPES.h model.h renderer.h
	cc68x -g -c tst_rend.c

renderer.o: renderer.c TYPES.h model.h renderer.h
	cc68x -g -c renderer.c

raster.o: raster.c TYPES.h raster.h
	cc68x -g -c raster.c

model.o: model.c TYPES.h model.h
	cc68x -g -c model.c

a_map.o: a_map.c bitmaps.h
	cc68x -g -c a_map.c

s_map.o: s_map.c bitmaps.h
	cc68x -g -c s_map.c

d_map.o: d_map.c bitmaps.h
	cc68x -g -c d_map.c

f_map.o: f_map.c bitmaps.h
	cc68x -g -c f_map.c

one_map.o: one_map.c bitmaps.h
	cc68x -g -c one_map.c

x_map.o: x_map.c bitmaps.h
	cc68x -g -c x_map.c

zro_map.o: zro_map.c bitmaps.h
	cc68x -g -c zro_map.c