# Executable file produced
TARGET=tst_mod

# Object files needed for target 
OBJECTS=tst_mod.o model.o events.o

# C compiler and flags
CC=cc68x
CFLAGS=-g

# Building the target
all: clean $(TARGET)

# Linking target executable from object files 
$(TARGET): $(OBJECTS) 
	$(CC) $(OBJECTS) -o $(TARGET) 

# Compiling object files
tst_mod.o: tst_mod.c model.h events.h 
	$(CC) $(CFLAGS) -c tst_mod.c 

model.o: model.c model.h types.h 
	$(CC) $(CFLAGS) -c model.c 

events.o: events.c model.h types.h 
	$(CC) $(CFLAGS) -c events.c 

# Cleaning up the old object files and executable
clean:
	$(RM) *.o tst_mod 
