all: 
	make clean 
	make model

clean:
	!Rm *.o
	!Rm model

model: tst_mod.o model.o events.o
	cc68x tst_mod.o model.o events.o -o model

tst_mod.o: tst_mod.c events.h 
	cc68x -g -c tst_mod.c

model.o: model.c model.h 
	cc68x -g -c model.c
	
events.o: events.c events.h 
	cc68x -g -c events.c