# Variable declarations
TARGET_A=vbl
OBJECTS_A=vbl.o vblisr.o music.o psg.o songdat.o

CC=cc68x
CFLAGS=-g

# Building the target
all: clean $(TARGET_A) 

# Linking target executables from object files
$(TARGET_A): $(OBJECTS_A)
	$(CC) $(OBJECTS_A) -o $(TARGET_A)

# Compiling object files 
vbl.o: vbl.c psg.h music.h sndconst.h songdat.h types.h
	$(CC) $(CFLAGS) -c vbl.c 

vblisr.o: vblisr.s 
	gen -D -L2 vblisr.s

psg.o: psg.c psg.h types.h
	$(CC) $(CFLAGS) -c psg.c

music.o: music.c music.h psg.h types.h songdat.h sndconst.h
	$(CC) $(CFLAGS) -c music.c 

songdat.o: songdat.c songdat.h sndconst.h types.h
	$(CC) $(CFLAGS) -c songdat.c 


# Cleaning up the old object files and executable
clean:
	$(RM) *.o $(TARGET_A)

# DON'T DELETE THIS LINE OR IT BREAKS